flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: false
    statuses:
      - type: project
        target: 80% # the default target for the project
        threshold: 2% # the allowed drop from the target
      - type: patch
        target: 75%
  # in general these individual flags should correspond to pytest markers
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: agentjobs
      statuses:
        - type: project
          target: 45%
        - type: patch
          target: 60%
