from __future__ import annotations

from http import HTTPStatus
from typing import TYPE_CHECKING
from uuid import UUID

import great_expectations.expectations as gxe
import pytest

from great_expectations_cloud.agent.actions.generate_expectations_action import (
    CREATED_VIA_EXPECT_AI,
)
from great_expectations_cloud.agent.models import CreatedResource
from great_expectations_cloud.agent.services.expectation_draft_config_service import (
    CreatedResourceTypes,
    ExpectationDraftConfigError,
    ExpectationDraftConfigService,
)

if TYPE_CHECKING:
    from pytest_mock import MockerFixture

    from tests.agent.conftest import MockCreateSessionType


@pytest.mark.unit
def test_create_single_expectation_draft_config_success(
    base_url: str,
    auth_key: str,
    service_organization_id: UUID,
    service_workspace_id: UUID,
    mock_context,
    mocker: MockerFixture,
    mock_create_session: MockCreateSessionType,
):
    # Arrange
    mock_data_source = mocker.Mock()
    mock_asset = mocker.Mock()
    mock_asset.id = UUID("12345678-1234-5678-9abc-123456789012")
    mock_data_source.get_asset.return_value = mock_asset
    mock_context.data_sources.get.return_value = mock_data_source

    # Mock ge_cloud_config
    mock_ge_cloud_config = mocker.Mock()
    mock_ge_cloud_config.base_url = base_url
    mock_ge_cloud_config.organization_id = str(service_organization_id)
    mock_ge_cloud_config.workspace_id = str(service_workspace_id)
    mock_ge_cloud_config.access_token = auth_key
    mock_context.ge_cloud_config = mock_ge_cloud_config

    mock_expectation = mocker.Mock(spec=gxe.UnexpectedRowsExpectation)
    mock_expectation.configuration.to_json_dict.return_value = {
        "type": "unexpected_rows_expectation",
        "unexpected_rows_query": "SELECT * FROM {batch} WHERE condition = false",
        "description": "Test expectation",
    }

    # Mock the HTTP session response
    expected_response_data = {"data": [{"id": "draft-config-id-12345"}]}
    _session = mock_create_session(
        "great_expectations_cloud.agent.services.expectation_draft_config_service",
        "post",
        HTTPStatus.CREATED,
        expected_response_data,
    )

    service = ExpectationDraftConfigService(context=mock_context, created_via=CREATED_VIA_EXPECT_AI)

    # Action
    result = service.create_single_expectation_draft_config(
        data_source_name="test_datasource",
        data_asset_name="test_asset",
        expectation=mock_expectation,
        event_id="test-event-123",
    )

    # Assert
    assert isinstance(result, CreatedResource)
    assert result.resource_id == "draft-config-id-12345"
    assert result.type == CreatedResourceTypes.EXPECTATION_DRAFT_CONFIG

    # Verify the correct API call was made
    expected_url = f"{base_url}/api/v1/organizations/{service_organization_id}/workspaces/{service_workspace_id}/expectation-draft-configs"
    _session.post.assert_called_once()
    call_args = _session.post.call_args
    assert call_args[1]["url"] == expected_url

    # Verify the Agent-Job-Id header is passed correctly
    assert "headers" in call_args[1]
    assert call_args[1]["headers"]["Agent-Job-Id"] == "test-event-123"

    # Verify the payload structure
    payload = call_args[1]["json"]
    assert "data" in payload
    assert len(payload["data"]) == 1
    draft_config = payload["data"][0]
    assert draft_config["asset_id"] == str(mock_asset.id)
    assert draft_config["organization_id"] == str(service_organization_id)
    assert "draft_expectation" in draft_config

    # Verify draft expectation structure
    draft_expectation = draft_config["draft_expectation"]
    assert draft_expectation["expectation_type"] == "unexpected_rows_expectation"
    assert draft_expectation["autogenerated"] is True
    assert draft_expectation["created_via"] == CREATED_VIA_EXPECT_AI


@pytest.mark.unit
def test_create_expectation_draft_configs_multiple(
    base_url: str,
    auth_key: str,
    service_organization_id: UUID,
    service_workspace_id: UUID,
    mock_context,
    mocker: MockerFixture,
    mock_create_session: MockCreateSessionType,
):
    mock_data_source = mocker.Mock()
    mock_asset = mocker.Mock()
    mock_asset.id = UUID("abcdefab-cdef-1234-5678-abcdefabcdef")

    mock_context.data_sources.get.return_value = mock_data_source
    mock_data_source.get_asset.return_value = mock_asset

    # Mock ge_cloud_config
    mock_ge_cloud_config = mocker.Mock()
    mock_ge_cloud_config.base_url = base_url
    mock_ge_cloud_config.organization_id = str(service_organization_id)
    mock_ge_cloud_config.workspace_id = str(service_workspace_id)
    mock_ge_cloud_config.access_token = auth_key
    mock_context.ge_cloud_config = mock_ge_cloud_config

    expectation1 = gxe.ExpectColumnValuesToBeBetween(
        column="test_column", min_value=1, max_value=100
    )
    expectation2 = gxe.ExpectColumnValuesToNotBeNull(column="another_column")

    # Mock the HTTP session response
    expected_response_data = {
        "data": [
            {"id": "draft-config-id-1"},
            {"id": "draft-config-id-2"},
        ]
    }
    _session = mock_create_session(
        "great_expectations_cloud.agent.services.expectation_draft_config_service",
        "post",
        HTTPStatus.CREATED,
        expected_response_data,
    )

    service = ExpectationDraftConfigService(context=mock_context, created_via=CREATED_VIA_EXPECT_AI)

    # Action
    results = service.create_expectation_draft_configs(
        data_source_name="test_datasource",
        data_asset_name="test_asset",
        expectations=[expectation1, expectation2],
        event_id="test-event-456",
    )

    # Assert
    mock_context.data_sources.get.assert_called_once_with("test_datasource")
    mock_data_source.get_asset.assert_called_once_with("test_asset")

    assert len(results) == 2
    assert all(isinstance(result, CreatedResource) for result in results)
    assert results[0].resource_id == "draft-config-id-1"
    assert results[1].resource_id == "draft-config-id-2"
    assert all(result.type == CreatedResourceTypes.EXPECTATION_DRAFT_CONFIG for result in results)

    # Verify the correct API call was made
    expected_url = f"{base_url}/api/v1/organizations/{service_organization_id}/workspaces/{service_workspace_id}/expectation-draft-configs"
    _session.post.assert_called_once()
    call_args = _session.post.call_args
    assert call_args[1]["url"] == expected_url

    # Verify the Agent-Job-Id header is passed correctly
    assert "headers" in call_args[1]
    assert call_args[1]["headers"]["Agent-Job-Id"] == "test-event-456"

    # Verify the payload contains multiple expectations
    payload = call_args[1]["json"]
    assert "data" in payload
    assert len(payload["data"]) == 2

    for draft_config in payload["data"]:
        assert draft_config["asset_id"] == str(mock_asset.id)
        assert draft_config["organization_id"] == str(service_organization_id)
        assert "draft_expectation" in draft_config

        draft_expectation = draft_config["draft_expectation"]

        assert draft_expectation["autogenerated"] is True
        assert draft_expectation["created_via"] == CREATED_VIA_EXPECT_AI
        assert "type" not in draft_expectation  # Should be renamed to expectation_type
        assert "expectation_type" in draft_expectation  # Should have been renamed from 'type'

    expectation_types = [
        config["draft_expectation"]["expectation_type"] for config in payload["data"]
    ]
    assert "expect_column_values_to_be_between" in expectation_types
    assert "expect_column_values_to_not_be_null" in expectation_types

    assert len(results) == 2
    assert all(isinstance(result, CreatedResource) for result in results)
    assert results[0].resource_id == "draft-config-id-1"
    assert results[1].resource_id == "draft-config-id-2"
    assert all(result.type == CreatedResourceTypes.EXPECTATION_DRAFT_CONFIG for result in results)


@pytest.mark.unit
def test_create_expectation_draft_config_api_failure(
    base_url: str,
    auth_key: str,
    service_organization_id: UUID,
    service_workspace_id: UUID,
    mock_context,
    mocker: MockerFixture,
    mock_create_session: MockCreateSessionType,
):
    # Arrange
    mock_data_source = mocker.Mock()
    mock_asset = mocker.Mock()
    mock_asset.id = UUID("abcdefab-cdef-1234-5678-abcdefabcdef")
    mock_data_source.get_asset.return_value = mock_asset
    mock_context.data_sources.get.return_value = mock_data_source

    # Mock ge_cloud_config
    mock_ge_cloud_config = mocker.Mock()
    mock_ge_cloud_config.base_url = base_url
    mock_ge_cloud_config.organization_id = str(service_organization_id)
    mock_ge_cloud_config.workspace_id = str(service_workspace_id)
    mock_ge_cloud_config.access_token = auth_key
    mock_context.ge_cloud_config = mock_ge_cloud_config

    mock_expectation = mocker.Mock(spec=gxe.UnexpectedRowsExpectation)
    mock_expectation.configuration.to_json_dict.return_value = {
        "type": "unexpected_rows_expectation",
        "unexpected_rows_query": "SELECT * FROM {batch} WHERE condition = false",
        "description": "Test expectation",
    }

    # Mock the HTTP session to return an error
    _session = mock_create_session(
        "great_expectations_cloud.agent.services.expectation_draft_config_service",
        "post",
        HTTPStatus.BAD_REQUEST,
        {"error": "Invalid request"},
    )

    service = ExpectationDraftConfigService(context=mock_context, created_via=CREATED_VIA_EXPECT_AI)

    # Action & Assert
    with pytest.raises(ExpectationDraftConfigError) as exc_info:
        service.create_single_expectation_draft_config(
            data_source_name="test_datasource",
            data_asset_name="test_asset",
            expectation=mock_expectation,
            event_id="test-event-error",
        )

    # Verify the exception contains the expected information
    assert "Could not create expectation draft config" in str(exc_info.value)
    assert "400" in str(exc_info.value)
