name: containerize-agent

on:
  push:
    branches:
      # - main
      - add-docker-compose-and-agent-job-test

jobs:
  containerize-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: great_expectations_cloud/agent/Dockerfile
          platforms: linux/amd64
          load: true
          tags: greatexpectations/agent:latest

      - name: Test New Agent Image
        run: |
          docker compose up -d
          pytest /test/agent/jobs/test_job_processing.py

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: great_expectations_cloud/agent/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: greatexpectations/agent:0.1.2,greatexpectations/agent:latest
