name: publish-to-pypi

# TODO: Set this to manually trigger once we cutover and go live
on:
  push:
    branches:
      - main

jobs:
  pypi-test-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python

      - name: Build distributions
        run: poetry build

      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # TODO: remove this one we are publishing to pypy
          # repository-url: https://test.pypi.org/legacy/
          skip-existing: true # prevent against pushing duplicate versions
